version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Copy Docker images
          command: cicd/copy-docker.sh
workflows:
  version: 2
  test_and_push:
    jobs:
      - build
