version: 2
jobs:
  copy-docker:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Copy Docker images
          command: src/cicd/copy-docker.sh
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo dummy build
workflows:
  version: 2
  test_and_push:
    jobs:
      - copy-docker:
          filters:
            branches:
              only: master
      - build:
          requires:
          - copy-docker
