version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo dummy build
  copy-docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Copy Docker images
          command: src/cicd/copy-docker.sh
workflows:
  version: 2
  test_and_push:
    jobs:
      - build:
      - copy-docker:
          filters:
            branches:
              only: master
